### ISSUE TITLE
Please use only lowercase letters in your composer.json package name parameter

### ISSUE THREAD

**Issue by ThomasNegeli** [brideo/Brideo_CmsPermissions#1]
Otherwise packagist or private proxies have problems including your module
You should use
`"name": "brideo/cmspermissions"`

**Comment by brideo** [comment]
Hey mate sorry about that. I'm out right now so can fix later, feel free to submit a pull request if how have the time!  :)

**Comment by ThomasNegeli** [comment]
#2 Created a pull request
